import { getActivitySnapshot } from "@/lib/activity";
import { getServerSnapshot } from "@/lib/server";
import { getChargerSnapshot } from "@/lib/anker";
import { getPowerBankSnapshot } from "@/lib/powerbank";
import { getRecentlyPlayed } from "@/lib/apple-music-store";
import { getNowWatching, getWatching } from "@/lib/emby";
import { getGithubChart } from "@/lib/github-chart";
import { getPlaying, getPlayingNow } from "@/lib/playstation";
import { getTrophies } from "@/lib/trophies";
import { getDesktopPayload, getNowListeningSnapshot, getTimezonePayload } from "@/lib/telemetry";
import { getVibeCodingSnapshot } from "@/lib/vibecoding";
import { getVibeCodingYear } from "@/lib/vibecoding-year-store";

export const desktopStatus = getDesktopPayload;
export const activityStatus = getActivitySnapshot;
export const serverStatus = getServerSnapshot;
export const chargerStatus = getChargerSnapshot;
export const powerBankStatus = getPowerBankSnapshot;
export const listeningStatus = getRecentlyPlayed;
export const nowListeningStatus = getNowListeningSnapshot;
export const timezoneStatus = getTimezonePayload;
export const vibeCodingStatus = getVibeCodingSnapshot;
export const vibeCodingYearStatus = getVibeCodingYear;
export const watchingStatus = getWatching;
export const nowWatchingStatus = getNowWatching;
export const playingStatus = getPlaying;
export const playingNowStatus = getPlayingNow;
export const trophiesStatus = getTrophies;
export const githubChartStatus = getGithubChart;
