name = "dev-router"
main = "src/index.ts"
compatibility_date = "2026-09-08"
workers_dev = false

[[services]]
binding = "API"
service = "api"

[[services]]
binding = "INGRESS"
service = "ingress"

[[services]]
binding = "COLLECTOR"
service = "collector"

[[services]]
binding = "COLLECTOR_RPC"
service = "collector"
entrypoint = "Collector"
