name = "am-motion-artwork"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
  { pattern = "am-motion-artwork.homepage.lyjw.llc", custom_domain = true }
]

[observability]
enabled = true
