name = "collector"
main = "src/index.ts"
compatibility_date = "2026-09-08"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
workers_dev = false

[triggers]
crons = ["* * * * *"]

[vars]
STORAGE_PREFIX = "lyjwpage"
APPLE_MUSIC_STOREFRONT = "cn"
CLOUDFLARE_ACCOUNT_ID = "209f2c881b1c494fec50851c067b3266"
VERCEL_PROJECT_ID = "prj_r6sFPPmanb9zm3hzYAHAmp3KsIiC"
VERCEL_TEAM_ID = "team_kfTnkK6X9bbqSbkgAhq7SxCd"
SENTRY_CRON_CHECKINS = "false"
SENTRY_DSN = "https://23b24c339292701f7b84adea24780773@o4511888459890688.ingest.us.sentry.io/4512164070948864"

[[services]]
binding = "CORE"
service = "api"
entrypoint = "StateCore"

[[kv_namespaces]]
binding = "COLLECTOR_KV"
id = "0f9b584f71634776ba3bc081a7aa4498"

[[kv_namespaces]]
binding = "LAG"
id = "e9c72a9517884aeb95db7386b630a691"

[[kv_namespaces]]
binding = "CREDENTIALS"
id = "c24d1670d97b4649ab5aa4c0944dfbfc"

[[d1_databases]]
binding = "HISTORY"
database_name = "lyjwpage-history"
database_id = "bf3a227f-d12e-428a-8f4e-0f56b97464df"

[alias]
"@/lib/storage-driver" = "./src/storage-driver.ts"
"@/lib/apple-developer-token" = "./src/apple-developer-token.ts"
"@/lib/apple-music-credentials" = "./src/apple-music-credentials.ts"

[version_metadata]
binding = "CF_VERSION_METADATA"

[observability]
enabled = true
