name: iPhoneTelemetryHub
options:
  bundleIdPrefix: com.liangyangjunwei
  deploymentTarget:
    iOS: "27.0"
  createIntermediateGroups: true
  groupSortPosition: none

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: 2VTXNMR2GL
    MARKETING_VERSION: "2.0.4"
    CURRENT_PROJECT_VERSION: "6"
    GENERATE_INFOPLIST_FILE: NO

targets:
  iPhoneTelemetryHub:
    type: application
    platform: iOS
    sources:
      - path: App/iPhoneTelemetryHub
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.liangyangjunwei.iPhoneTelemetryHub
        PRODUCT_NAME: iPhoneTelemetryHub
        INFOPLIST_FILE: App/iPhoneTelemetryHub/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/iPhoneTelemetryHub/iPhoneTelemetryHub.entitlements
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
