name = "ingress"
main = "src/index.ts"
compatibility_date = "2026-09-08"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
workers_dev = true

routes = [
  { pattern = "ingest.homepage.lyjw.llc", custom_domain = true }
]

[vars]
EMBY_PUBLIC_URL = "https://emby.lyjw131.com"
SENTRY_DSN = "https://13ba806bda9ae5a9086576b2e3d23cfb@o4511888459890688.ingest.us.sentry.io/4512132602855424"
ACCESS_TEAM_DOMAIN = "https://lyjw2007.cloudflareaccess.com"
ACCESS_AUD = "a1557bcf1114491b462c7ee722ae97032405c43fa831812c8403e6d7366fba01"

[vars.ACCESS_CLIENTS]
"259e8eb2abeb45b1d0033c69e0989fb5.access" = ["ingest:quest"]
"f9ace27b1709a23e651094cca5d41013.access" = ["ingest:playstation"]
"267c1f87539a30657986e9d719663dcd.access" = ["ingest:agents-otlp"]
"4ec7a9e98b7d3bc641c5eb97fddcb4f7.access" = ["ingest:mac"]
"8dfbbba29d501f75ff7763a598d6ada0.access" = ["ingest:iphone"]
"01031f46aaeb93099ea40287f2c85f61.access" = ["ingest:emby"]
"fd30812b4dfd526c6ffd7801f07a6563.access" = ["ingest:server"]
"ef47dda27da6a8428cee4cdebbf2951b.access" = ["ingest:agents"]
"04fb01940873a28a7ef42f9b5bfbad9d.access" = ["ingest:homepod"]
"c9437b45b762a36199e243df0df35ec4.access" = ["internal:site-deployed"]

[[services]]
binding = "CORE"
service = "api"
entrypoint = "StateCore"

[[services]]
binding = "COLLECTOR"
service = "collector"
entrypoint = "Collector"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "lyjw-homepage"

[[kv_namespaces]]
binding = "LAG"
id = "e9c72a9517884aeb95db7386b630a691"

[[kv_namespaces]]
binding = "CREDENTIALS"
id = "c24d1670d97b4649ab5aa4c0944dfbfc"

[[d1_databases]]
binding = "HISTORY"
database_name = "lyjwpage-history"
database_id = "bf3a227f-d12e-428a-8f4e-0f56b97464df"

[version_metadata]
binding = "CF_VERSION_METADATA"

[observability]
enabled = true

[previews.vars]
PREVIEW_WORKER = "true"
