/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5a0d84a6f93ce1abba02d0584bb163ba)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "https://lyjw.me,https://lyjw131.com,https://dev.lyjw.me,https://*.vercel.app";
	ONLINE_COUNTER: DurableObjectNamespace<import("./src/index").OnlineCounterRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "OnlineCounterRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
